# Generated by Django 6.0.5 on 2026-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.URLField(verbose_name='链接')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='friend_links/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TendCode', max_length=100, verbose_name='站点名称')),
                ('site_description', models.TextField(blank=True, verbose_name='站点描述')),
                ('site_keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('author_name', models.CharField(default='技术博主', max_length=50, verbose_name='作者名称')),
                ('author_bio', models.TextField(blank=True, verbose_name='作者简介')),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='作者头像')),
                ('icp_number', models.CharField(blank=True, max_length=50, verbose_name='ICP备案号')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('notice', models.TextField(blank=True, verbose_name='网站公告')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='建站日期')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
