# Generated by Django 6.0.5 on 2026-05-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('weibo', '微博')], max_length=20, verbose_name='提供商')),
                ('uid', models.CharField(max_length=100, verbose_name='第三方用户ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '社交账号',
                'verbose_name_plural': '社交账号',
                'unique_together': {('provider', 'uid')},
            },
        ),
    ]
