# Generated by Django 6.0.5 on 2026-06-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('wechat', '微信')], max_length=20, verbose_name='提供商'),
        ),
    ]
