# Generated by Django 6.0.5 on 2026-05-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='主机名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='上报令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监控服务器',
                'verbose_name_plural': '监控服务器',
            },
        ),
        migrations.CreateModel(
            name='MonitorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(verbose_name='CPU使用率')),
                ('memory_percent', models.FloatField(verbose_name='内存使用率')),
                ('disk_percent', models.FloatField(verbose_name='磁盘使用率')),
                ('load_avg', models.FloatField(default=0, verbose_name='负载')),
                ('network_in', models.BigIntegerField(default=0, verbose_name='入网流量(bytes)')),
                ('network_out', models.BigIntegerField(default=0, verbose_name='出网流量(bytes)')),
                ('uptime', models.BigIntegerField(default=0, verbose_name='运行时间(秒)')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.monitorserver')),
            ],
            options={
                'verbose_name': '监控指标',
                'verbose_name_plural': '监控指标',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['server', '-reported_at'], name='monitoring__server__87ed5d_idx')],
            },
        ),
    ]
