# Generated by Django 6.0.5 on 2026-05-15 17:44

import apps.articles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=apps.articles.models.SearchVectorField(blank=True, null=True, verbose_name='搜索向量'),
        ),
    ]
