# Generated by Django 6.0.5 on 2026-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_nickname_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='封面'),
        ),
    ]
